In [1]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame

In [2]:
df = pd.read_csv(
    '../../../data/celebrity_deaths_2016.csv',
    usecols= ['dateofdeath', 'age']
)

In [3]:
df.head()

  dateofdeath age
0  2016-01-01  71
1  2016-01-01  74
2  2016-01-01  79
3  2016-01-01  45
4  2016-01-01  83

In [4]:
df.dtypes

dateofdeath    str
age            str
dtype: object

In [5]:
# is there any NaN in the age or possible to convert int16/int8 format

df.isna().sum()

dateofdeath     0
age            27
dtype: int64

In [6]:
df['year'] = df['dateofdeath'].str.slice(0,4)
df['month'] = df['dateofdeath'].str.slice(5,7)
df['day'] = df['dateofdeath'].str.slice(-2) # NOTE: this counts from the back

df

     dateofdeath age  year month day
0     2016-01-01  71  2016    01  01
1     2016-01-01  74  2016    01  01
2     2016-01-01  79  2016    01  01
3     2016-01-01  45  2016    01  01
4     2016-01-01  83  2016    01  01
...          ...  ..   ...   ...  ..
6538  2016-12-27  74  2016    12  27
6539  2016-12-27  85  2016    12  27
6540  2016-12-27  83  2016    12  27
6541  2016-12-27  23  2016    12  27
6542  2016-12-27  84  2016    12  27

[6543 rows x 5 columns]

In [7]:
df.age.max()

'99'

In [8]:
df = df.reset_index()

In [9]:
# Make the month column the index of the data frame.
df = (
    df
    .set_index('month')
    .sort_index()
    ['age'].apply(lambda x: np.nan if not str(x).isdigit() else x).dropna().astype('int8')  
)


# There were some values in the age column that looked like numbers (e.g., 8889),
# but they were not valid digits because they contained whitespace or other non-visible characters.

In [10]:
df.info()

<class 'pandas.Series'>
Index: 6481 entries, 01 to 12
Series name: age
Non-Null Count  Dtype
--------------  -----
6481 non-null   int8
dtypes: int8(1)
memory usage: 57.0+ KB

In [11]:
df

month
01    71
01    47
01    87
01    90
01    73
      ..
12    63
12    20
12    57
12    78
12    84
Name: age, Length: 6481, dtype: int8

In [12]:
# Find the average age of celebrities who died during that period (February–July 2016)

df.loc[slice('02','07')].mean()

np.float64(77.17887409200968)