In [1]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame

In [2]:
df = pd.read_csv(
    '../../../data/olympic_athlete_events.csv',
    sep= ',',
    header= 0,
    usecols= ['Age', 'Height', 'Team', 'Year', 'Season', 'Sport', 'Medal']
)

# Read in our Olympic data again.
# – Only use these columns: Age, Height, Team, Year, Season, Sport, Medal.
# – Only include games from 1980 to the present.
# – Only include data from these countries: Great Britain, France, United States, Switzerland, China, and India.

df = df.loc[(df['Year'] >= 1980) & (df['Team'].isin(["Great Britain", "France", "United States", "Switzerland", "China", "India"]))]

In [3]:
df

         Age  Height           Team  Year  Season                 Sport Medal
0       24.0   180.0          China  1992  Summer            Basketball   NaN
1       23.0   170.0          China  2012  Summer                  Judo   NaN
10      31.0   188.0  United States  1992  Winter  Cross Country Skiing   NaN
11      31.0   188.0  United States  1992  Winter  Cross Country Skiing   NaN
12      31.0   188.0  United States  1992  Winter  Cross Country Skiing   NaN
...      ...     ...            ...   ...     ...                   ...   ...
270996  24.0   186.0    Switzerland  2002  Winter              Biathlon   NaN
270997  24.0   186.0    Switzerland  2002  Winter              Biathlon   NaN
271021  26.0   175.0    Switzerland  1984  Summer               Sailing   NaN
271036  22.0   183.0         France  1998  Winter            Ice Hockey   NaN
271037  26.0   183.0         France  2002  Winter            Ice Hockey   NaN

[27893 rows x 7 columns]

In [4]:
# What was the average age of Olympic athletes?

df.groupby('Team')['Age'].mean().sort_values()

Team
China            22.930242
India            25.165344
France           25.588394
Great Britain    25.597681
United States    25.753982
Switzerland      25.939108
Name: Age, dtype: float64

In [5]:
# In which country do players appear to consistently be the youngest?

df.pivot_table(
    index = 'Year',
    columns = 'Team',
    values = 'Age'
).round(2)

Team  China  France  Great Britain  India  Switzerland  United States
Year
1980  21.87   23.52          22.88  25.51        24.56          22.77
1984  22.08   24.37          24.45  24.91        23.59          24.44
1988  22.36   24.52          25.44  24.00        26.22          24.90
1992  21.96   25.14          25.58  24.18        25.41          25.47
1994  20.63   24.60          25.28    NaN        25.50          24.98
1996  22.02   25.30          26.75  24.63        27.12          26.27
1998  21.78   25.46          27.24  16.00        25.64          25.15
2000  22.52   25.98          26.41  25.40        27.38          26.58
2002  23.13   25.74          26.83  20.00        26.24          25.73
2004  23.01   26.14          26.30  24.73        27.34          26.44
2006  23.46   26.30          26.85  25.20        26.28          25.64
2008  23.90   26.29          25.20  25.40        27.31          26.23
2010  23.24   25.91          26.15  25.67        26.55          25.84
2012  23.89   26.61          25.92  25.64        27.17          26.46
2014  23.40   25.71          25.63  25.00        25.86          26.19
2016  23.87   27.10          26.65  26.10        25.89          26.22

In [6]:
# How tall were the tallest athletes in each sport in each year?

df.pivot_table(
    index= 'Sport',
    columns= 'Year',
    values= 'Height',
    aggfunc= 'max'
)

Year,1980,1984,1988,1992,1994,1996,1998,2000,2002,2004,2006,2008,2010,2012,2014,2016
Sport,,,,,,,,,,,,,,,,
Alpine Skiing,184.0,184.0,185.0,185.0,188.0,NaN,188.0,NaN,189.0,NaN,193.0,NaN,193.0,NaN,200.0,NaN
Archery,185.0,188.0,188.0,191.0,NaN,191.0,NaN,191.0,NaN,193.0,NaN,193.0,NaN,193.0,NaN,188.0
Athletics,197.0,203.0,203.0,200.0,NaN,198.0,NaN,197.0,NaN,203.0,NaN,203.0,NaN,208.0,NaN,203.0
Badminton,NaN,NaN,NaN,186.0,NaN,189.0,NaN,187.0,NaN,190.0,NaN,190.0,NaN,191.0,NaN,191.0
Baseball,NaN,NaN,NaN,198.0,NaN,195.0,NaN,206.0,NaN,NaN,NaN,198.0,NaN,NaN,NaN,NaN
Basketball,196.0,216.0,216.0,216.0,NaN,216.0,NaN,226.0,NaN,226.0,NaN,226.0,NaN,221.0,NaN,218.0
Beach Volleyball,NaN,NaN,NaN,NaN,NaN,193.0,NaN,195.0,NaN,192.0,NaN,202.0,NaN,202.0,NaN,188.0
Biathlon,190.0,190.0,188.0,192.0,192.0,NaN,192.0,NaN,192.0,NaN,193.0,NaN,193.0,NaN,193.0,NaN
Bobsleigh,NaN,184.0,NaN,NaN,NaN,NaN,198.0,NaN,190.0,NaN,193.0,NaN,191.0,NaN,189.0,NaN
Boxing,190.0,195.0,196.0,193.0,NaN,191.0,NaN,198.0,NaN,190.0,NaN,203.0,NaN,201.0,NaN,200.0
Canoeing,203.0,203.0,203.0,203.0,NaN,205.0,NaN,203.0,NaN,190.0,NaN,200.0,NaN,194.0,NaN,191.0
Cross Country Skiing,185.0,189.0,186.0,190.0,190.0,NaN,185.0,NaN,188.0,NaN,188.0,NaN,193.0,NaN,193.0,NaN
Curling,NaN,NaN,NaN,NaN,NaN,NaN,188.0,NaN,193.0,NaN,183.0,NaN,189.0,NaN,192.0,NaN
Cycling,190.0,190.0,195.0,192.0,NaN,189.0,NaN,192.0,NaN,192.0,NaN,196.0,NaN,198.0,NaN,196.0
Diving,176.0,175.0,178.0,183.0,NaN,183.0,NaN,183.0,NaN,182.0,NaN,185.0,NaN,178.0,NaN,188.0
Equestrianism,179.0,187.0,187.0,184.0,NaN,196.0,NaN,187.0,NaN,196.0,NaN,196.0,NaN,196.0,NaN,196.0
Fencing,193.0,208.0,208.0,193.0,NaN,196.0,NaN,196.0,NaN,196.0,NaN,196.0,NaN,197.0,NaN,197.0
Figure Skating,183.0,182.0,180.0,182.0,182.0,NaN,182.0,NaN,183.0,NaN,188.0,NaN,188.0,NaN,193.0,NaN
Football,NaN,188.0,190.0,193.0,NaN,191.0,NaN,193.0,NaN,180.0,NaN,193.0,NaN,195.0,NaN,188.0
Freestyle Skiing,NaN,NaN,NaN,190.0,186.0,NaN,193.0,NaN,193.0,NaN,183.0,NaN,193.0,NaN,188.0,NaN
Golf,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,193.0
Gymnastics,180.0,179.0,181.0,178.0,NaN,180.0,NaN,175.0,NaN,176.0,NaN,184.0,NaN,184.0,NaN,184.0
Handball,197.0,200.0,200.0,198.0,NaN,203.0,NaN,199.0,NaN,199.0,NaN,201.0,NaN,204.0,NaN,202.0
Hockey,179.0,190.0,189.0,193.0,NaN,196.0,NaN,196.0,NaN,196.0,NaN,189.0,NaN,189.0,NaN,193.0
Ice Hockey,193.0,193.0,195.0,194.0,195.0,NaN,195.0,NaN,190.0,NaN,195.0,NaN,196.0,NaN,198.0,NaN
Judo,196.0,204.0,204.0,196.0,NaN,205.0,NaN,202.0,NaN,202.0,NaN,203.0,NaN,203.0,NaN,203.0
Luge,188.0,188.0,183.0,188.0,188.0,NaN,188.0,NaN,185.0,NaN,188.0,NaN,188.0,NaN,188.0,NaN
Modern Pentathlon,185.0,188.0,190.0,190.0,NaN,185.0,NaN,186.0,NaN,191.0,NaN,188.0,NaN,188.0,NaN,194.0
Nordic Combined,193.0,183.0,193.0,183.0,180.0,NaN,181.0,NaN,183.0,NaN,183.0,NaN,190.0,NaN,190.0,NaN
Rhythmic Gymnastics,NaN,172.0,170.0,172.0,NaN,172.0,NaN,173.0,NaN,178.0,NaN,177.0,NaN,173.0,NaN,177.0
Rowing,198.0,205.0,205.0,205.0,NaN,205.0,NaN,204.0,NaN,207.0,NaN,207.0,NaN,206.0,NaN,207.0
Rugby Sevens,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,195.0
Sailing,186.0,198.0,198.0,195.0,NaN,203.0,NaN,201.0,NaN,198.0,NaN,194.0,NaN,195.0,NaN,197.0
Shooting,183.0,189.0,190.0,190.0,NaN,195.0,NaN,188.0,NaN,192.0,NaN,192.0,NaN,198.0,NaN,200.0
Short Track Speed Skating,NaN,NaN,NaN,182.0,183.0,NaN,183.0,NaN,188.0,NaN,186.0,NaN,186.0,NaN,189.0,NaN
Skeleton,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,188.0,NaN,185.0,NaN,185.0,NaN,190.0,NaN
Ski Jumping,185.0,180.0,185.0,190.0,185.0,NaN,185.0,NaN,185.0,NaN,190.0,NaN,190.0,NaN,190.0,NaN
Snowboarding,NaN,NaN,NaN,NaN,NaN,NaN,190.0,NaN,190.0,NaN,186.0,NaN,190.0,NaN,188.0,NaN
Softball,NaN,NaN,NaN,NaN,NaN,182.0,NaN,185.0,NaN,188.0,NaN,191.0,NaN,NaN,NaN,NaN
Speed Skating,185.0,190.0,193.0,193.0,186.0,NaN,186.0,NaN,193.0,NaN,188.0,NaN,203.0,NaN,193.0,NaN
Swimming,194.0,200.0,200.0,201.0,NaN,201.0,NaN,201.0,NaN,202.0,NaN,203.0,NaN,203.0,NaN,206.0
Synchronized Swimming,NaN,178.0,180.0,180.0,NaN,181.0,NaN,181.0,NaN,177.0,NaN,175.0,NaN,178.0,NaN,177.0
Table Tennis,NaN,NaN,185.0,193.0,NaN,193.0,NaN,188.0,NaN,193.0,NaN,192.0,NaN,188.0,NaN,186.0
Taekwondo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,198.0,NaN,198.0,NaN,201.0,NaN,201.0,NaN,197.0
Tennis,NaN,NaN,193.0,200.0,NaN,200.0,NaN,198.0,NaN,188.0,NaN,198.0,NaN,206.0,NaN,196.0
Trampolining,NaN,NaN,NaN,NaN,NaN,NaN,NaN,175.0,NaN,172.0,NaN,179.0,NaN,179.0,NaN,178.0
Triathlon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,192.0,NaN,191.0,NaN,196.0,NaN,191.0,NaN,191.0
Volleyball,NaN,203.0,203.0,202.0,NaN,203.0,NaN,204.0,NaN,209.0,NaN,210.0,NaN,206.0,NaN,209.0
Water Polo,NaN,198.0,205.0,205.0,NaN,200.0,NaN,200.0,NaN,203.0,NaN,201.0,NaN,203.0,NaN,206.0
Weightlifting,180.0,188.0,190.0,190.0,NaN,195.0,NaN,182.0,NaN,180.0,NaN,177.0,NaN,189.0,NaN,187.0
Wrestling,205.0,190.0,193.0,193.0,NaN,194.0,NaN,196.0,NaN,195.0,NaN,203.0,NaN,203.0,NaN,188.0

In [7]:
# How many medals did each country earn each year?

(
    df
    .dropna(subset='Medal')
    .pivot_table(
        index='Team',
        columns='Year',
        values='Medal',
        aggfunc='size'
    )
)

Year,1980,1984,1988,1992,1994,1996,1998,2000,2002,2004,2006,2008,2010,2012,2014,2016
Team,,,,,,,,,,,,,,,,
China,NaN,74.0,50.0,73.0,3.0,94.0,14.0,65.0,14.0,82.0,9.0,170.0,15.0,117.0,12.0,109.0
France,30.0,70.0,31.0,65.0,11.0,49.0,13.0,64.0,13.0,53.0,15.0,77.0,14.0,78.0,18.0,96.0
Great Britain,48.0,71.0,54.0,50.0,3.0,26.0,4.0,52.0,6.0,55.0,1.0,81.0,1.0,122.0,10.0,145.0
India,16.0,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,1.0,NaN,3.0,NaN,6.0,NaN,2.0
Switzerland,5.0,17.0,24.0,2.0,8.0,11.0,10.0,14.0,20.0,5.0,15.0,11.0,12.0,4.0,28.0,11.0
United States,30.0,359.0,212.0,236.0,19.0,255.0,30.0,240.0,70.0,259.0,48.0,309.0,89.0,238.0,52.0,256.0

#### Beyond the exercise_1
##### Create a pivot table that shows the number of medals each team won per year, with the index including the year and the season in which the games took place.

In [8]:
(
    df
    .dropna(subset= 'Medal')
    .pivot_table(
        index= ['Year', 'Season'],
        columns= 'Team',
        values= 'Medal',
        aggfunc= 'size'
    )
)

Team         China  France  Great Britain  India  Switzerland  United States
Year Season
1980 Summer    NaN    29.0           47.0   16.0          2.0            NaN
     Winter    NaN     1.0            1.0    NaN          3.0           30.0
1984 Summer   74.0    67.0           71.0    NaN         13.0          352.0
     Winter    NaN     3.0            NaN    NaN          4.0            7.0
1988 Summer   50.0    29.0           54.0    NaN          8.0          207.0
     Winter    NaN     2.0            NaN    NaN         16.0            5.0
1992 Summer   70.0    55.0           50.0    NaN          1.0          222.0
     Winter    3.0    10.0            NaN    NaN          1.0           14.0
1994 Winter    3.0    11.0            3.0    NaN          8.0           19.0
1996 Summer   94.0    49.0           26.0    1.0         11.0          255.0
1998 Winter   14.0    13.0            4.0    NaN         10.0           30.0
2000 Summer   65.0    64.0           52.0    1.0         14.0          240.0
2002 Winter   14.0    13.0            6.0    NaN         20.0           70.0
2004 Summer   82.0    53.0           55.0    1.0          5.0          259.0
2006 Winter    9.0    15.0            1.0    NaN         15.0           48.0
2008 Summer  170.0    77.0           81.0    3.0         11.0          309.0
2010 Winter   15.0    14.0            1.0    NaN         12.0           89.0
2012 Summer  117.0    78.0          122.0    6.0          4.0          238.0
2014 Winter   12.0    18.0           10.0    NaN         28.0           52.0
2016 Summer  109.0    96.0          145.0    2.0         11.0          256.0

#### Beyond the exercise_2
##### Create a pivot table that shows both the average age and the average height per year per team.

In [9]:
(
    df.
    pivot_table(
        index= 'Year',
        columns= 'Team',
        values= ['Age', 'Height'],
        aggfunc= 'mean'
    ).round(2)
)

        Age                                                        Height  \
Team  China France Great Britain  India Switzerland United States   China
Year
1980  21.87  23.52         22.88  25.51       24.56         22.77  162.64
1984  22.08  24.37         24.45  24.91       23.59         24.44  171.61
1988  22.36  24.52         25.44  24.00       26.22         24.90  171.30
1992  21.96  25.14         25.58  24.18       25.41         25.47  171.00
1994  20.63  24.60         25.28    NaN       25.50         24.98  169.23
1996  22.02  25.30         26.75  24.63       27.12         26.27  170.40
1998  21.78  25.46         27.24  16.00       25.64         25.15  168.91
2000  22.52  25.98         26.41  25.40       27.38         26.58  170.96
2002  23.13  25.74         26.83  20.00       26.24         25.73  169.01
2004  23.01  26.14         26.30  24.73       27.34         26.44  172.75
2006  23.46  26.30         26.85  25.20       26.28         25.64  170.31
2008  23.90  26.29         25.20  25.40       27.31         26.23  176.02
2010  23.24  25.91         26.15  25.67       26.55         25.84  169.56
2012  23.89  26.61         25.92  25.64       27.17         26.46  175.45
2014  23.40  25.71         25.63  25.00       25.86         26.19  169.81
2016  23.87  27.10         26.65  26.10       25.89         26.22  174.99


Team  France Great Britain   India Switzerland United States
Year
1980  175.10        175.44  170.75      177.01        175.02
1984  176.28        174.41  169.40      173.42        176.88
1988  176.16        176.08  168.70      176.61        176.62
1992  175.23        176.15  172.50      175.33        176.40
1994  173.01        172.92     NaN      174.11        175.44
1996  174.49        177.44  171.79      174.11        177.48
1998  174.83        173.76  183.00      174.28        173.47
2000  176.23        176.48  173.33      176.49        177.33
2002  175.77        173.06  183.00      176.19        173.77
2004  176.11        176.66  169.91      176.31        176.94
2006  174.04        176.11  167.80      176.01        173.87
2008  176.96        176.89  173.12      176.05        177.47
2010  174.77        176.34  176.00      176.62        174.49
2012  177.34        177.76  173.57      177.10        178.09
2014  173.77        173.43  170.00      174.05        174.71
2016  177.75        176.40  169.97      173.86        177.79

#### Beyond the exercise_3
##### Create a pivot table that shows the average age and the average height per year, per team, broken up by year and season.

In [10]:
(
    df.
    pivot_table(
        index= ['Year', 'Season'],
        columns= 'Team',
        values= ['Age', 'Height'],
        aggfunc= 'mean'
    ).round(2)
)

               Age                                                        \
Team         China France Great Britain  India Switzerland United States
Year Season
1980 Summer    NaN  23.70         22.76  25.51       25.33           NaN
     Winter  21.87  22.75         23.57    NaN       23.48         22.77
1984 Summer  22.10  24.30         24.46  24.91       23.65         24.60
     Winter  21.99  24.79         24.35    NaN       23.36         23.56
1988 Summer  22.46  24.50         25.78  24.07       27.60         25.21
     Winter  19.60  24.58         23.42  22.67       24.39         23.62
1992 Summer  21.96  25.55         25.86  24.43       26.33         25.63
     Winter  21.93  23.95         23.82  20.50       24.07         24.93
1994 Winter  20.63  24.60         25.28    NaN       25.50         24.98
1996 Summer  22.02  25.30         26.75  24.63       27.12         26.27
1998 Winter  21.78  25.46         27.24  16.00       25.64         25.15
2000 Summer  22.52  25.98         26.41  25.40       27.38         26.58
2002 Winter  23.13  25.74         26.83  20.00       26.24         25.73
2004 Summer  23.01  26.14         26.30  24.73       27.34         26.44
2006 Winter  23.46  26.30         26.85  25.20       26.28         25.64
2008 Summer  23.90  26.29         25.20  25.40       27.31         26.23
2010 Winter  23.24  25.91         26.15  25.67       26.55         25.84
2012 Summer  23.89  26.61         25.92  25.64       27.17         26.46
2014 Winter  23.40  25.71         25.63  25.00       25.86         26.19
2016 Summer  23.87  27.10         26.65  26.10       25.89         26.22

             Height
Team          China  France Great Britain   India Switzerland United States
Year Season
1980 Summer     NaN  175.89        175.51  170.75      180.53           NaN
     Winter  162.64  171.42        174.52     NaN      171.59        175.02
1984 Summer  172.07  176.52        174.44  169.40      173.93        177.18
     Winter  166.29  174.64        174.12     NaN      171.38        175.21
1988 Summer  171.28  176.19        176.64  168.70      176.83        177.10
     Winter  175.00  176.06        172.78     NaN      176.30        174.52
1992 Summer  170.95  176.01        176.56  172.50      175.58        176.94
     Winter  171.79  172.96        173.25     NaN      174.97        174.47
1994 Winter  169.23  173.01        172.92     NaN      174.11        175.44
1996 Summer  170.40  174.49        177.44  171.79      174.11        177.48
1998 Winter  168.91  174.83        173.76  183.00      174.28        173.47
2000 Summer  170.96  176.23        176.48  173.33      176.49        177.33
2002 Winter  169.01  175.77        173.06  183.00      176.19        173.77
2004 Summer  172.75  176.11        176.66  169.91      176.31        176.94
2006 Winter  170.31  174.04        176.11  167.80      176.01        173.87
2008 Summer  176.02  176.96        176.89  173.12      176.05        177.47
2010 Winter  169.56  174.77        176.34  176.00      176.62        174.49
2012 Summer  175.45  177.34        177.76  173.57      177.10        178.09
2014 Winter  169.81  173.77        173.43  170.00      174.05        174.71
2016 Summer  174.99  177.75        176.40  169.97      173.86        177.79