In [1]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame

In [2]:
df = pd.read_csv(
    '../../../data/nyc-parking-violations-2020.csv',
    header= 0,
    sep= ',',
    usecols= [
        'Date First Observed',
        'Plate ID',
        'Registration State',
        'Issue Date',
        'Vehicle Make',
        'Street Name',
        'Vehicle Color']
)

In [3]:
df.head()

,Plate ID,Registration State,Issue Date,Vehicle Make,Street Name,Date First Observed,Vehicle Color
0,J58JKX,NJ,05/08/1972 12:00:00 AM,HONDA,43 ST,0,BK
1,KRE6058,PA,08/29/1977 12:00:00 AM,ME/BE,UNION ST,0,BLK
2,444326R,NJ,10/03/1988 12:00:00 AM,LEXUS,CLERMONT AVENUE,0,BLACK
3,F728330,OH,01/03/1990 12:00:00 AM,CHEVR,DIVISION AVE,0,NaN
4,FMY9090,NY,02/14/1990 12:00:00 AM,JEEP,GRAND ST,0,GREY

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12495734 entries, 0 to 12495733
Data columns (total 7 columns):
 #   Column               Dtype
---  ------               -----
 0   Plate ID             str
 1   Registration State   str
 2   Issue Date           str
 3   Vehicle Make         str
 4   Street Name          str
 5   Date First Observed  int64
 6   Vehicle Color        str
dtypes: int64(1), str(6)
memory usage: 667.3 MB

In [5]:
# Set the data frame’s index to the Issue Date column.

df = df.set_index('Issue Date')
df

,Plate ID,Registration State,Vehicle Make,Street Name,Date First Observed,Vehicle Color
Issue Date,,,,,,
05/08/1972 12:00:00 AM,J58JKX,NJ,HONDA,43 ST,0,BK
08/29/1977 12:00:00 AM,KRE6058,PA,ME/BE,UNION ST,0,BLK
10/03/1988 12:00:00 AM,444326R,NJ,LEXUS,CLERMONT AVENUE,0,BLACK
01/03/1990 12:00:00 AM,F728330,OH,CHEVR,DIVISION AVE,0,NaN
02/14/1990 12:00:00 AM,FMY9090,NY,JEEP,GRAND ST,0,GREY
...,...,...,...,...,...,...
01/03/2040 12:00:00 AM,62161MM,NY,FORD,3RD AVE,0,BR
04/19/2045 12:00:00 AM,GYE7330,NY,HONDA,PELHAM PARK DR,0,BLK
01/17/2049 12:00:00 AM,HNY4802,NY,FORD,LYDIG AVE,0,GY
12/19/2063 12:00:00 AM,T687081C,NY,TOYOT,E 68 STREET,0,BLK
06/04/2064 12:00:00 AM,3497ZN,WA,UTILI,W/S/O 182 STREET,0,WHITE

In [6]:
# Determine what three makes were most frequently ticketed on January 2, 2020.

df.loc['01/02/2020 12:00:00 AM', 'Vehicle Make'].value_counts().head(3)

Vehicle Make
TOYOT    3829
HONDA    3593
FORD     3164
Name: count, dtype: int64

In [7]:
# Determine the five streets on which cars got the most tickets on June 1, 2020.

df.loc['06/01/2020 12:00:00 AM', 'Street Name'].value_counts().head(5)

Street Name
WB CONDUIT BLVD @ LI    1068
SB WEST ST @ LEROY S     335
EB HORACE HARDING EX     273
EB QUEENS BLVD @ 82N     245
WB ATLANTIC AVE @ CL     229
Name: count, dtype: int64

In [8]:
# Set the index to Vehicle Color.

df = df.reset_index().set_index('Vehicle Color')
df

# NOTE: Reuven called reset_index() before setting the new index, which is very useful.
# In my version, the issue_date column got lost because I didn’t reset the index.

,Issue Date,Plate ID,Registration State,Vehicle Make,Street Name,Date First Observed
Vehicle Color,,,,,,
BK,05/08/1972 12:00:00 AM,J58JKX,NJ,HONDA,43 ST,0
BLK,08/29/1977 12:00:00 AM,KRE6058,PA,ME/BE,UNION ST,0
BLACK,10/03/1988 12:00:00 AM,444326R,NJ,LEXUS,CLERMONT AVENUE,0
NaN,01/03/1990 12:00:00 AM,F728330,OH,CHEVR,DIVISION AVE,0
GREY,02/14/1990 12:00:00 AM,FMY9090,NY,JEEP,GRAND ST,0
...,...,...,...,...,...,...
BR,01/03/2040 12:00:00 AM,62161MM,NY,FORD,3RD AVE,0
BLK,04/19/2045 12:00:00 AM,GYE7330,NY,HONDA,PELHAM PARK DR,0
GY,01/17/2049 12:00:00 AM,HNY4802,NY,FORD,LYDIG AVE,0
BLK,12/19/2063 12:00:00 AM,T687081C,NY,TOYOT,E 68 STREET,0
WHITE,06/04/2064 12:00:00 AM,3497ZN,WA,UTILI,W/S/O 182 STREET,0

In [9]:
df.index.unique()

Index(['BK', 'BLK', 'BLACK', nan, 'GREY', 'GY', 'WH', 'RED', 'GRAY', 'TAN',
       ...
       'GYHNU', 'BLF', 'BL9', 'LTBR0', 'BK;', 'GLKPP', '';', 'WHGY8', 'ORYW',
       'CH'],
      dtype='str', name='Vehicle Color', length=1897)

In [10]:
# Determine the most common make of vehicles that were either red or blue.

df.loc[['RED', 'BLUE'], ['Vehicle Make']].value_counts().head(1)

Vehicle Make
HONDA           39353
Name: count, dtype: int64

####  Beyond the exercise_1

##### What three car makes were most often ticketed from January 2 through January 10?

In [11]:
df = df.reset_index().set_index('Issue Date').sort_index()

df.loc['01/02/2020 12:00:00 AM':'01/10/2020 12:00:00 PM', 'Vehicle Make'].value_counts().head(3)

Vehicle Make
FORD     38958
TOYOT    37096
HONDA    35962
Name: count, dtype: int64

####  Beyond the exercise_2

##### How many tickets did the second-most-ticketed car get in 2020? And why am I not interested in the most-ticketed plate?) What state was that car from, and was it always ticketed in the same location?

In [12]:
df.loc['01/01/2020 12:00:00 AM':'12:31:2020 12:00:00 AM', 'Plate ID'].value_counts().head(2)

# The 8881 BLABLANKPLATE are not interesting

Plate ID
BLANKPLATE    8881
2704819       1535
Name: count, dtype: int64

In [13]:
# What state was that car from?, and was it always ticketed in the same location?

df[df['Plate ID'] == '2704819']['Registration State']

Issue Date
01/02/2020 12:00:00 AM    IN
01/02/2020 12:00:00 AM    IN
01/02/2020 12:00:00 AM    IN
01/02/2020 12:00:00 AM    IN
01/02/2020 12:00:00 AM    IN
                          ..
12/31/2019 12:00:00 AM    IN
12/31/2019 12:00:00 AM    IN
12/31/2019 12:00:00 AM    IN
12/31/2019 12:00:00 AM    IN
12/31/2019 12:00:00 AM    IN
Name: Registration State, Length: 1535, dtype: str

In [14]:
# , and was it always ticketed in the same location?

df[df['Plate ID'] == '2704819']['Street Name'].value_counts()

# My answer is no for this question.

Street Name
8th Ave        395
Penn Plz       230
7th Ave         92
9th Ave         63
Broadway        57
              ...
5 AVE            1
W 47 STREET      1
10TH AVE         1
N/S 34 ST        1
W 43 ST          1
Name: count, Length: 113, dtype: int64