In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
df = pd.read_csv(
    '../../../data/nyc_taxi_2019-01.csv',
     engine = 'pyarrow',
    dtype_backend = 'pyarrow',
    usecols = ['passenger_count', 'trip_distance', 'total_amount'] 
)

In [3]:
len(df)

7667792

In [4]:
# For each number of passengers, find the mean cost of a taxi ride. Sort this
# result from lowest (i.e., cheapest) to highest (i.e., most expensive).

df.groupby('passenger_count').mean().sort_values(by = 'total_amount')

                 trip_distance  total_amount
passenger_count
6                     2.842335     15.437892
5                     2.865741      15.54694
3                     2.840698     15.604015
1                     2.779088     15.609601
4                     2.853084     15.650307
2                     2.880572     15.831294
0                     2.651561     18.663658
9                     1.486667     31.094444
7                     2.561579     48.278421
8                     3.142759     64.105517

In [5]:
df.groupby('passenger_count').agg('mean').sort_values(by = 'total_amount')

                 trip_distance  total_amount
passenger_count
6                     2.842335     15.437892
5                     2.865741      15.54694
3                     2.840698     15.604015
1                     2.779088     15.609601
4                     2.853084     15.650307
2                     2.880572     15.831294
0                     2.651561     18.663658
9                     1.486667     31.094444
7                     2.561579     48.278421
8                     3.142759     64.105517

In [6]:
# Sort the results again by increasing the number of passengers.
df.groupby('passenger_count').mean().sort_index()

                 trip_distance  total_amount
passenger_count
0                     2.651561     18.663658
1                     2.779088     15.609601
2                     2.880572     15.831294
3                     2.840698     15.604015
4                     2.853084     15.650307
5                     2.865741      15.54694
6                     2.842335     15.437892
7                     2.561579     48.278421
8                     3.142759     64.105517
9                     1.486667     31.094444

In [7]:
# Create a new column, trip_distance_group, in which the values are
# short (< 2 miles),
# medium (>=2 miles and <= 10 miles), and
# long (> 10 miles).

df['trip_distance_group'] = 'medium'
df.loc[df['trip_distance'] < 2, 'trip_distance_group'] = 'short'
df.loc[df['trip_distance'] > 10, 'trip_distance_group'] = 'long'
df.sample(10)

         passenger_count  trip_distance  total_amount trip_distance_group
1945854                1            1.8          11.8               short
2859237                2           3.11         17.16              medium
6559182                6            0.6          6.36               short
2303363                6           1.35          9.75               short
5509909                6           2.26          10.3              medium
3483518                1            0.5          6.96               short
3349763                1           4.59         20.16              medium
1077660                1           1.69          10.5               short
5369889                1           2.56          14.3              medium
2680619                1           0.54           7.3               short

In [8]:
# What is the average number of passengers per trip length category?
# Sort this result from highest (most passengers) to lowest (fewest passengers).

df.groupby('trip_distance_group')['passenger_count'].mean()

trip_distance_group
long      1.590035
medium    1.576764
short     1.559943
Name: passenger_count, dtype: double[pyarrow]

In [10]:
df.groupby('trip_distance_group').mean().sort_values(by = 'passenger_count', ascending = False)

                     passenger_count  trip_distance  total_amount
trip_distance_group
long                        1.590035      15.549428     57.800367
medium                      1.576764       3.927226     20.009066
short                       1.559943       1.072269      9.652103