In [1]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame

In [2]:
df = pd.read_json('../../../data/cities.json')

In [3]:
#for digit grouping and control floating-point numbers

pd.set_option('display.float_format', '{:,.2f}'.format)

df['population'] = df['population'].astype('float64')

In [4]:
df

,city,growth_from_2000_to_2013,latitude,longitude,population,rank,state
0,New York,4.8%,40.71,-74.01,"8,405,837.00",1,New York
1,Los Angeles,4.8%,34.05,-118.24,"3,884,307.00",2,California
2,Chicago,-6.1%,41.88,-87.63,"2,718,782.00",3,Illinois
3,Houston,11.0%,29.76,-95.37,"2,195,914.00",4,Texas
4,Philadelphia,2.6%,39.95,-75.17,"1,553,165.00",5,Pennsylvania
...,...,...,...,...,...,...,...
995,Weslaco,28.8%,26.16,-97.99,"37,093.00",996,Texas
996,Keizer,14.4%,44.99,-123.03,"37,064.00",997,Oregon
997,Spanish Fork,78.1%,40.11,-111.65,"36,956.00",998,Utah
998,Beloit,2.9%,42.51,-89.03,"36,888.00",999,Wisconsin
999,Panama City,0.1%,30.16,-85.66,"36,877.00",1000,Florida

### Task_1
#### What are the mean and median populations for these 1,000 largest cities? What does that tell you?

In [5]:
print(df['population'].describe())

# mean is ~2x of the median so there are some cities with real high population (outliers)

count       1,000.00
mean      131,132.44
std       341,690.19
min        36,877.00
25%        49,697.75
50%        68,207.00
75%       109,885.00
max     8,405,837.00
Name: population, dtype: float64

### Task_2
#### Along these lines, if you remove the 50 most populous cities, what happens to the mean population? What happens to the median?

In [6]:
cleaned_df = df.drop(df.sort_values(by= 'population').tail(50).index)#.reset_index(drop= True)
cleaned_df

,city,growth_from_2000_to_2013,latitude,longitude,population,rank,state
50,New Orleans,-21.6%,29.95,-90.07,"378,715.00",51,Louisiana
51,Bakersfield,48.4%,35.37,-119.02,"363,630.00",52,California
52,Tampa,16.0%,27.95,-82.46,"352,957.00",53,Florida
53,Honolulu,-6.2%,21.31,-157.86,"347,884.00",54,Hawaii
54,Aurora,24.4%,39.73,-104.83,"345,803.00",55,Colorado
...,...,...,...,...,...,...,...
995,Weslaco,28.8%,26.16,-97.99,"37,093.00",996,Texas
996,Keizer,14.4%,44.99,-123.03,"37,064.00",997,Oregon
997,Spanish Fork,78.1%,40.11,-111.65,"36,956.00",998,Utah
998,Beloit,2.9%,42.51,-89.03,"36,888.00",999,Wisconsin
999,Panama City,0.1%,30.16,-85.66,"36,877.00",1000,Florida

In [7]:
cleaned_df['population'].describe()
# now the mean in only  1.3x of the median

count       950.00
mean     87,027.39
std      58,652.96
min      36,877.00
25%      48,989.50
50%      65,796.00
75%     100,842.00
max     378,715.00
Name: population, dtype: float64

### Task_3
#### What is the northernmost city, and where does it rank?

In [8]:
df.loc[df['latitude'] == df['latitude'].max()]

,city,growth_from_2000_to_2013,latitude,longitude,population,rank,state
62,Anchorage,15.4%,61.22,-149.90,"300,950.00",63,Alaska

### Task_4
#### Which state has the largest number of cities on this list?

In [9]:
df.groupby('state')[['city']].count().sort_values(by= 'city', ascending= False).head(1)

            city
state
California   212

### Task_5
#### Which state has the smallest number of cities on this list?

In [10]:
df.groupby('state')[['city']].count().sort_values(by= 'city').head(1)

        city
state
Alaska     1

### Beyond the exercise_1


#### Convert the `growth_from_2000_to_2013` column into a floating-point number. Then find the mean and median changes in city size between 2000 and 2013. If a city has no recorded growth, set it to 0.

In [ ]:
df['growth_from_2000_to_2013'] = (
    df['growth_from_2000_to_2013']
    .replace('', '0%')
    .str.slice(0, -1)
    .astype('float16')
)

count   1,000.00
mean       22.94
std        86.69
min       -27.09
25%         2.80
50%         9.65
75%        24.52
max     2,504.00
Name: growth_from_2000_to_2013, dtype: float64

In [16]:
df['growth_from_2000_to_2013'].describe().loc[['mean', '50%']]

mean   22.94
50%     9.65
Name: growth_from_2000_to_2013, dtype: float64